.TH "/home/tom/Work/pifacehome/libmcp23s17/src/ Directory Reference" 3 "Fri Mar 7 2014" "Version 0.2.0" "libmcp23s17" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tom/Work/pifacehome/libmcp23s17/src/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmcp23s17\&.c\fP"
.br
.ti -1c
.RI "file \fBmcp23s17\&.h\fP"
.br
.RI "\fIA simple static library for controlling an MCP23S17 port expander over SPI\&. \fP"
.in -1c
